import java.util.Random;
/**
 *  Computes some statistics about families in which the parents decide 
 *  to have children until they have at least one child of each gender.
 *  The program expects to get two command-line arguments: an int value
 * 	that determines how many families to simulate, and an int value
 *  that serves as the seed of the random numbers generated by the program.
 *  Example usage: % java OneOfEachStats 1000 1
 */
public class OneOfEachStats {
	public static void main (String[] args) {
		// Gets the two command-line arguments
		int num = Integer.parseInt(args[0]);
		int seed = Integer.parseInt(args[1]);
		// Initailizes a random numbers generator with the given seed value
        Random generator = new Random(seed);  
		
		//// In the previous version of this program, you used a statement like:
		//// double rnd = Math.random();
		//// Where "rnd" is the variable that stores the generated random value.
		//// In this version of the program, replace this statement with:
		//// double rnd = generator.nextDouble();
		//// This statement will generate a random value in the range [0,1),
		//// just like you had in the previous version, except that the 
		//// randomization will be based on the given seed.
		//// This is the only change that you have to do in the program.
		String gender;
		String wantedGender;
		int count2 = 0;
		int count3 = 0;
		int count4Plus = 0;
		int sumOfIterations = 0;
		for(int i =0; i < num; i++)
		{
			int kids = 1;
			int random = (int)(generator.nextDouble() * 10);
			if(random >= 5)
			{
				gender = "g";
				wantedGender = "b";
			}
			else 
			{
				gender = "b";
				wantedGender = "g";

			}

			//System.out.print(gender + " ");

			while(!gender.equals(wantedGender))
			{
				random = (int)(generator.nextDouble() * 10);
				kids++;
				if(random >= 5)
				{
					gender = "g";
				}
				else 
				{
					gender = "b";
				}

				//System.out.print(gender + " ");
			}
			if(kids == 2)
				count2++;

			else if(kids == 3)
				count3++;

			else count4Plus++;

			sumOfIterations += kids;
			//System.out.println();
			//System.out.println(sumOfIterations);
		}

		
		double avarage = ((double)sumOfIterations)/num;

		System.out.println("Average: " + avarage + " children to get at least one of each gender." );
		System.out.println("Number of families with 2 children: " + count2);
		System.out.println("Number of families with 3 children: " + count3);
		System.out.println("Number of families with 4 or more children: " + count4Plus);

		String maxKids;
		if(Math.max(count2, Math.max(count3, count4Plus))== count2)
		{
			maxKids = "2.";
		}
		else if(Math.max(count2, Math.max(count3, count4Plus))== count3)
		{
			maxKids = "3.";
		}
		else
		{
			maxKids = "4 or more.";
		}

		System.out.println("The most common number of children is " + maxKids);

		    
	}
}
